import platform 
print(platform.architecture())
print(platform.processor())
print(platform.node())
#print(platform.freedesktop_os_release())
print(platform.machine())
print(platform.python_compiler())
print(platform.system())
print(platform.uname())
print(platform.python_branch())
print(platform.python_build())
print(platform.mac_ver())
print(platform.python_implementation())
print(platform.python_revision())
#print(platform.system_alias())
print(platform.java_ver())